name: memex-explorer
channels:
    - blaze
    - memex
    - quasiben
dependencies:
    - python=3.4.2
    - nutch
    - ache=0.1.0
    - django=1.7.3
    - pytest
    - pip
    - pip:
        - coverage
        - pytest-cov
        - pytest-django
        - pytest-ordering
        - django-crispy-forms
