name: memex-explorer
channels:
    - blaze
    - memex
    - quasiben
dependencies:
    - python=2.7.8
    - nutch
    - ache=0.1.0
    - django=1.7.3
    - solr=4.10.2
    - pytest
    - pip
    - pip:
        - selenium
        - coverage
        - pytest-cov
        - pytest-django
        - pytest-ordering
        - django-crispy-forms
        - coveralls
